# Project information
site_name: pyGeckoCrypto
# define TOC or order of website-
nav:
  - Home: index.md
  - API Reference: APIreference.md

site_author: Abe Alexander
site_description: >-
  A library for rendering Youtube and reference sites in Jupyter notebooks

# Repository
repo_name: abealexander/pyGeckoCrypto
repo_url: https://github.com/abealexander/pyGeckoCrypto

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abealexander
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/abe-alexander/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/abealexander"  target="_blank" rel="noopener">Abe Alexander</a>